# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Project Graveyard
email: britown@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for me to discuss failed creative pursuits, wax philosophical
  about potentially successful ones, and convince myself that 
  I am always working toward the latter.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://britown88.github.io" # the base hostname & protocol for your site
twitter_username: britown88
github_username:  britown88

# Build settings
markdown: kramdown
